### ISSUE TITLE
Review story SF-190: Tests for the GitHub review issue parser

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#46]
Story being reviewed: [SF-190](https://jira.salsitasoft.com/browse/SF-190)

SF-Issue-Tracker: JIRA
SF-Story-Key: SF-190

The commits to be reviewed are following:
- [x] fe7c63e: Make tests a part of the build process
- [x] 36507e0: github/issues: Add tests
- [x] f150f6a: github/issues: Refactor tests to fix review issues
- [x] 5fd6c3e: github/issues: tests: Pull stuff into setup helpers

----------

The content above was generated by SalsaFlow.
You can insert custom description here, but not above the separator.

**Comment by tchap** [comment]
The following commits were added to this issue:
* f150f6a: github/issues: Refactor tests to fix review issues

**Comment by tchap** [comment]
The following commits were added to this issue:
* 5fd6c3e: github/issues: tests: Pull stuff into setup helpers

**Comment by mbernat** [comment]
I'm not sure what's the current state of the tests is, but I guess you got my basic point: move all the nontrivial logic into the code itself and make the tests just really dumb comparisons.
Leaving the issue open in case you want to improve the tests further (in particular, really check out the property-based testing, I think you'll like it; although I'm not sure about the quality of these libs in Go). If not, just close the issue yourself.

**Comment by mbernat** [comment]
Oh, there's actually quickcheck in the standard library! http://golang.org/pkg/testing/quick/
But might still be useful to try https://github.com/arschles/gogenerate as well since it says:

"gogenerate generators generate strongly typed values, so composing them to create new, more complex generators is easier. The newly composed generators can then also be converted to testing/quick generators."

**Comment by tchap** [comment]
Yeah, I am looking into it. But it's restricted to functions returning just a single value, which might be ok, will try. If it's too much of a PITA, I will just leave it as it is.

**Comment by mbernat** [comment]
Sure, I have no idea how usable it will be. But glad you're giving it a shot, hopefully it won't be too terrible.

**Comment by tchap** [comment]
Actually it doesn't make sense to generate random input here since the parser would just return immediately. I am leaving this idea and closing this. Perhaps next time I will use it when it makes sense.

**Comment by mbernat** [comment]
Uh, the point is to generate random stuff of the kind you need (i.e. optionally include parts of the commit info, random number of commits/blockers, etc.). Not totally random strings :D 

That being said, it's true that this is not the easiest type of code to test with this method. Anyway, just keep it in mind. It's really useful to test many things at once, so that you don't have to write similar unit tests all over again.

Just as a little appetizer, here's what kind of stuff it's really great for:
`quickCheck ((\s -> (reverse.reverse) s == s) :: [Char] -> Bool)`
Like this you'll check the property (that's why property-based testing) of the reverse function that calling it twice gives you back the original. Of course it doesn't mean it's correct but it rules out huge number of wrong implementation that you can never capture with unit tests.

**Comment by tchap** [comment]
Dunno really what is the added value in generating random GitHub issues. It will just keep returning parsing errors. I need to test first and foremost that it is able to parse expected review issue bodies. Of course that it's good it fails when it is expected to fail, but it's only a part of the whole picture, right?

**Comment by mbernat** [comment]
Look, you need to test your code somehow. If you want to do it with unit tests, you have to generate 100 clauses, so that you test at least something (actually a negligible portion of the code, even though we pretend that 100% line coverage means something). Are you going to write those 100 tests? No, you're not. Quickcheck gives you a way to kind of automate it. Again, how much it's useful depends on what you're testing. The closer the tested function will be to math and the more properties will it have, the easier it will be to test. The more arbitrary it is (imagine a huge switch in the body of that function), the less will quickcheck be able to help you.

Anyway, all of this was meant as a (hopefully) useful advice. Use it however you want ;)
